name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        install_components: 'beta'

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build and Push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mousecat-lab/mousecat-web:$GITHUB_SHA .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mousecat-lab/mousecat-web:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
          --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mousecat-lab/mousecat-web:$GITHUB_SHA \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --quiet
