name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        install_components: 'beta'

    - name: Configure Docker to use Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mousecat-lab/mousecat-lab:$GITHUB_SHA .

    - name: Push image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mousecat-lab/mousecat-lab:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/mousecat-lab/mousecat-lab:$GITHUB_SHA \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --quiet
