name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # O reemplaza por 'develop' si quieres desplegar desde esa rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        install_components: 'beta'

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
          --image=gcr.io/${{ secrets.GCP_PROJECT }}/[IMAGE_NAME] \
          --region=${{ secrets.GCP_REGION }} \
          --platform=managed \
          --quiet
